### ISSUE TITLE
Train model 

### ISSUE THREAD

**Issue by intvo** [lucasb-eyer/BiternionNet#2]
Can you upload the per trained model, also how can I train the model using our dataset. 
Please let me know

**Comment by lucasb-eyer** [comment]
Hi and sorry for the delay in answering.

This repository is meant to reproduce the experiments from the paper, but is not ideally suited to train your own models. Probably the [Experiments - TownCentre](https://github.com/lucasb-eyer/BiternionNet/blob/master/Experiments%20-%20TownCentre.ipynb) notebook is the closest to what you'd want.

But there is [another more practical implementation of BiternionNets here](https://github.com/VisualComputingInstitute/BiternionNets-ROS) with instructions on labeling and training your own model.

Finally, with a colleague we provide [an updated version of the above which uses PyTorch](https://github.com/sbreuers/BiternionNets-ROS/) that might be even simpler to use as it doesn't rely on my own (unsupported) deep-learning framework anymore.

Hope you'll find what you need there, sorry I don't have the bandwidth to provide full support.
